### ISSUE TITLE
Standard request `eth_maxPriorityFeePerGas` not supported

### ISSUE THREAD

**Issue by barakman** [sei-protocol/sei-chain#1611]
**Describe the bug**

Standard request `eth_maxPriorityFeePerGas` does not seem to be supported.
I have postulated that perhaps this chain doesn't support EIP-1559 altogether.
But your [Differences with Ethereum](https://v2.docs.sei.io/differences-with-ethereum) webpage does not mention any of that.

**To Reproduce**

After pip-installing web3.py v6.16.0, run:

```python
from web3 import Web3
web3 = Web3(Web3.HTTPProvider('https://evm-rpc.arctic-1.seinetwork.io/'))
print(web3.eth.max_priority_fee)
```

**Expected behavior**

A non-negative integer value should be printed in the console.

**Actual behavior**

The following stack-trace is printed in the console, indicating that the aforementioned request is not supported:
```
/usr/local/lib/python3.9/site-packages/web3/eth/eth.py:189: UserWarning: There was an issue with the method eth_maxPriorityFeePerGas. Calculating using eth_feeHistory.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/web3/eth/eth.py", line 187, in max_priority_fee
    return self._max_priority_fee()
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 329, in request_blocking
    return self.formatted_response(
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 278, in formatted_response
    raise MethodUnavailable(
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method eth_maxPriorityFeePerGas does not exist/is not available'}
/usr/local/lib/python3.9/site-packages/web3/eth/eth.py:189: UserWarning: There was an issue with the method eth_maxPriorityFeePerGas. Calculating using eth_feeHistory.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/web3/eth/eth.py", line 187, in max_priority_fee
    return self._max_priority_fee()
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 329, in request_blocking
    return self.formatted_response(
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 278, in formatted_response
    raise MethodUnavailable(
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method eth_maxPriorityFeePerGas does not exist/is not available'}
```

**Comment by philipsu522** [comment]
this is now supported: https://github.com/sei-protocol/sei-chain/blob/main/evmrpc/info.go#L178 thanks @yzang2019
