### ISSUE TITLE
[BUG] panic: recovered: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by mhmdbahja** [sei-protocol/sei-chain#1822]
**Seid version**
v5.7.5

**Chain ID**
pacific-1

**Go version**
go version go1.21.1 linux/amd64

**OS**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**Describe the bug**
I am getting an error when I run seid on the default config fro config.toml and app.toml using `seid start`

`panic: recovered: runtime error: integer divide by zero`

**To Reproduce**

cd ~/ && git clone https://github.com/sei-protocol/sei-chain.git
cd sei-chain
git checkout v5.7.5
make install
seid init node --chain-id pacific-1
wget -O genesis.json https://raw.githubusercontent.com/sei-protocol/testnet/main/pacific-1/genesis.json
mv genesis.json ~/.sei/config
sed -i '/^# Comma separated list of nodes to keep persistent connections to$/,/^$/ s/^persistent-peers = ""$/persistent-peers = "de8b1df70c7a8817ed121908e7c6e6059f4238f9@3.142.50.176:26656,7a962f3a928ca4e0e58355e6e798aba1ea253272@34.242.85.117:26656"/' ~/.sei/config/config.toml
sed -i 's/^sc-enable = false/sc-enable = true/' ~/.sei/config/app.toml

**Debug**
1. I have tried to change the GO version but sometimes I am getting an error in `make install` and sometimes the same error
2. I have tried different versions for seid
3. I have tried to change some configurations, and I have noticed the problem is gone if I enabled statesync using `enable = false`, but I need to spin up the archive node and I cant use state sync for my case

**Logs**

```
root@Ubuntu-2204-jammy-amd64-base ~/sei-chain # seid start
12:40PM INF --tracing not passed in, tracing is not enabled
12:40PM INF Creating node metrics provider
12:40PM INF Starting Process
12:40PM INF SeiDB SC is enabled, running node with StoreV2 commit store
INFO [08-17|12:40:06.926] [JOB 1] WAL file /root/.sei/data/receipt.db/000010.log with log number 000010 stopped reading at offset: 0; replayed 0 keys in 0 batches
12:40PM INF SeiDB load target memIAVL version 0, copyExisting = false

12:40PM INF Start catching up and replaying the MemIAVL changelog file
12:40PM INF Finished the replay and caught up to version 0
12:40PM INF starting node with ABCI Tendermint in-process
12:40PM INF Adding new peer de8b1df70c7a8817ed121908e7c6e6059f4238f9 with address mconn://de8b1df70c7a8817ed121908e7c6e6059f4238f9@3.142.50.176:26656 to peer store
 module=p2p
12:40PM INF Adding new peer 7a962f3a928ca4e0e58355e6e798aba1ea253272 with address mconn://7a962f3a928ca4e0e58355e6e798aba1ea253272@34.242.85.117:26656 to peer store
 module=p2p
12:40PM INF starting service impl=Node service=Node
12:40PM INF starting service impl=proxyClient module=proxy service=proxyClient
12:40PM INF starting service impl=localClient service=localClient
12:40PM INF starting service impl=EventBus module=eventbus service=EventBus
12:40PM INF starting service impl=PubSub module=events service=PubSub
12:40PM INF starting service impl=IndexerService module=txindex service=IndexerService
12:40PM INF ABCI Handshake App Info hash= height=0 module=handshaker protocol-version=0 software-version=v5.7.5
12:40PM INF ABCI Replay Blocks appHeight=0 module=handshaker stateHeight=0 storeHeight=0
12:40PM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/nonnegative-outstanding
12:40PM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/can-withdraw
12:40PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/reference-count
12:40PM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/module-account
12:40PM INF asserting crisis invariants inv=5/11 module=x/crisis name=staking/module-accounts
12:40PM INF asserting crisis invariants inv=6/11 module=x/crisis name=staking/nonnegative-power
12:40PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/positive-delegation
12:40PM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/delegator-shares
12:40PM INF asserting crisis invariants inv=9/11 module=x/crisis name=bank/nonnegative-outstanding
12:40PM INF asserting crisis invariants inv=10/11 module=x/crisis name=bank/total-supply
12:40PM INF asserting crisis invariants inv=11/11 module=x/crisis name=gov/module-account
12:40PM INF asserted all invariants duration=0.410958 height=0 module=x/crisis
12:40PM INF Current epoch 0
panic: recovered: runtime error: integer divide by zero
stack:
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func1({0x260d8c0, 0x4f0c640})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/recovery.go:91 +0x25
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func2({0x260d8c0?, 0x4f0c640?})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/recovery.go:40 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x260d8c0, 0x4f0c640}, 0xc000af5fe0?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/recovery.go:29 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x260d8c0, 0x4f0c640}, 0x1?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/recovery.go:34 +0x53
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x260d8c0, 0x4f0c640}, 0x0?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/recovery.go:34 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/baseapp.go:894 +0x36d
panic({0x260d8c0?, 0x4f0c640?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/auth/ante/setup.go:69 +0x1d8
panic({0x260d8c0?, 0x4f0c640?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cosmos/cosmos-sdk/store/types.(*infiniteMultiplierGasMeter).adjustGas(...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/store/types/gas.go:289
github.com/cosmos/cosmos-sdk/store/types.(*infiniteMultiplierGasMeter).ConsumeGas(0x18?, 0x1?, {0x29d393b?, 0x15?})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/store/types/gas.go:293 +0x50
github.com/cosmos/cosmos-sdk/store/gaskv.(*Store).Get(0xc000c41e60, {0xc00071d290, 0x15, 0x18})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/store/gaskv/store.go:42 +0x4a
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.GetAccount({{0x39812d8, 0xc0009296a0}, {0x39b1e70, 0xc0007c5b70}, {{0x39b1e70, 0xc0007c5b70}, 0xc000286708, {0x39812d8, 0xc000929720}, {0x3981300, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/auth/keeper/account.go:37 +0x13e
github.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.checkDeductFee({{0x399d108, 0xc0007661e0}, {0x7fd7546ffd40, 0xc000b1d6c0}, {0x3979840, 0xc000a99020}, {{0x39b1e70, 0xc0007c5b70}, 0xc000286708, {0x39812d8, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/auth/ante/fee.go:177 +0x3df
github.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.AnteHandle({{0x399d108, 0xc0007661e0}, {0x7fd7546ffd40, 0xc000b1d6c0}, {0x3979840, 0xc000a99020}, {{0x39b1e70, 0xc0007c5b70}, 0xc000286708, {0x39812d8, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/auth/ante/fee.go:139 +0x191
github.com/sei-protocol/sei-chain/app/antedecorators.GaslessDecorator.handleWrapped({{0xc000c18610, 0x1, 0x1}, {{0x39b1e70, 0xc0007c5b70}, {0x39812d8, 0xc000929790}, {0x3981328, 0xc000929840}, {{0x39b1e70, ...}, ...}, ...}, ...}, ...)
        /root/sei-chain/app/antedecorators/gasless.go:64 +0x167
github.com/sei-protocol/sei-chain/app/antedecorators.GaslessDecorator.AnteHandle({{0xc000c18610, 0x1, 0x1}, {{0x39b1e70, 0xc0007c5b70}, {0x39812d8, 0xc000929790}, {0x3981328, 0xc000929840}, {{0x39b1e70, ...}, ...}, ...}, ...}, ...)
        /root/sei-chain/app/antedecorators/gasless.go:51 +0x410
github.com/cosmos/cosmos-sdk/types.chainAnteDecoratorHandlers.func1({{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000c41d40}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/types/handler.go:81 +0x138
github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({_}, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000c41d40}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/auth/ante/setup.go:74 +0x250
github.com/cosmos/cosmos-sdk/types.WrappedAnteDecorator.AnteHandle(...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/types/handler.go:122
github.com/cosmos/cosmos-sdk/types.chainAnteDecoratorHandlers.func1({{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000c41d40}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/types/handler.go:81 +0x138
github.com/sei-protocol/sei-chain/x/evm/ante.EVMRouterDecorator.AnteHandle({_, _, _, _}, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000c41d40}, {{0x0, 0x0}, ...}, ...}, ...)
        /root/sei-chain/x/evm/ante/router.go:40 +0x24e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(_, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/baseapp.go:932 +0xcd9
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(_, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/abci.go:299 +0x3ed
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/genutil/gentx.go:113 +0x226
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x399d4d0, 0xc000a0c5d0}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/genutil/module.go:109 +0x13e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/types/module/module.go:426 +0x4c9
github.com/sei-protocol/sei-chain/app.(*App).InitChainer(_, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/sei-chain/app/app.go:1128 +0x334
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0003fedc0, {0x40?, 0x6?}, 0x6?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/abci.go:73 +0x5d9
github.com/tendermint/tendermint/internal/proxy.(*proxyClient).InitChain(0xc0001a5c00, {0x399d508, 0xc00017f450}, 0xc000f0d860?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/internal/proxy/client.go:129 +0x171
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).ReplayBlocks(_, {_, _}, {{{0xb, 0x0}, {0xc0009ee450, 0x11}}, {0xc000af7740, 0x9}, 0x1, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/internal/consensus/replay.go:312 +0xf35
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).Handshake(0xc000db1c38, {0x399d508, 0xc00017f450}, {0x39bfee0?, 0xc0001a5c00?})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/internal/consensus/replay.go:268 +0x3db
github.com/tendermint/tendermint/node.(*nodeImpl).OnStart(0xc000770380, {0x399d508, 0xc00017f450})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/node/node.go:510 +0x2d5
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000770380, {0x399d508?, 0xc00017f450})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/libs/service/service.go:117 +0x203
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x39c69d0, 0xc0006a7fb0}, {0xc000a12790, 0x9}, {0x39a5148, 0xc00062f570}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/server/start.go:418 +0xb30
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0007f3400?, {0x502fa60?, 0x0?, 0x0?})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/server/start.go:209 +0x899
github.com/spf13/cobra.(*Command).execute(0xc000a65200, {0x502fa60, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003d5200)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x4f50768?, {0xc0006362e0, 0xa})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/server/cmd/execute.go:35 +0x145
main.main()
        /root/sei-chain/cmd/seid/main.go:16 +0x2b
: panic

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/genutil/gentx.go:115 +0x325
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x399d4d0, 0xc000a0c5d0}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/x/genutil/module.go:109 +0x13e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/types/module/module.go:426 +0x4c9
github.com/sei-protocol/sei-chain/app.(*App).InitChainer(_, {{0x399d4d0, 0xc000a0c5d0}, {0x39bc510, 0xc000f0d920}, {{0x0, 0x0}, {0xc000af6b90, 0x9}, 0x0, ...}, ...}, ...)
        /root/sei-chain/app/app.go:1128 +0x334
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0003fedc0, {0x40?, 0x6?}, 0x6?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/baseapp/abci.go:73 +0x5d9
github.com/tendermint/tendermint/internal/proxy.(*proxyClient).InitChain(0xc0001a5c00, {0x399d508, 0xc00017f450}, 0xc000f0d860?)
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/internal/proxy/client.go:129 +0x171
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).ReplayBlocks(_, {_, _}, {{{0xb, 0x0}, {0xc0009ee450, 0x11}}, {0xc000af7740, 0x9}, 0x1, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/internal/consensus/replay.go:312 +0xf35
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).Handshake(0xc000db1c38, {0x399d508, 0xc00017f450}, {0x39bfee0?, 0xc0001a5c00?})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/internal/consensus/replay.go:268 +0x3db
github.com/tendermint/tendermint/node.(*nodeImpl).OnStart(0xc000770380, {0x399d508, 0xc00017f450})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/node/node.go:510 +0x2d5
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000770380, {0x399d508?, 0xc00017f450})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.6/libs/service/service.go:117 +0x203
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x39c69d0, 0xc0006a7fb0}, {0xc000a12790, 0x9}, {0x39a5148, 0xc00062f570}, ...}, ...)
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/server/start.go:418 +0xb30
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0007f3400?, {0x502fa60?, 0x0?, 0x0?})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/server/start.go:209 +0x899
github.com/spf13/cobra.(*Command).execute(0xc000a65200, {0x502fa60, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003d5200)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x4f50768?, {0xc0006362e0, 0xa})
        /root/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.31/server/cmd/execute.go:35 +0x145
main.main()
        /root/sei-chain/cmd/seid/main.go:16 +0x2b
```

**Comment by philipsu522** [comment]
hi @mhmdbahja is your goal to join the network (you can use state sync info [here](https://www.docs.sei.io/dev-node/join-a-network)) or is your goal to sync from genesis? If it's from genesis, you'll have to start with the correct version of seid which would be `2.0.48beta`.

**Comment by mhmdbahja** [comment]
@philipsu522 checkout to v2.0.48beta worked, thanks.
I am trying to sync from genesis, but right now the node cannot sync

`ERR failed to send request for peers err="no available peers to send a PEX request to (retrying)"`

I think there are no peers with genesis blocks
Any idea?

**Comment by Cordtus** [comment]
You will not find any node to sync from 0 with for sure. That is not the issue though, you just need better peers.

**Comment by cordt-sei** [comment]
> @philipsu522 checkout to v2.0.48beta worked, thanks. I am trying to sync from genesis, but right now the node cannot sync
> 
> `ERR failed to send request for peers err="no available peers to send a PEX request to (retrying)"`
> 
> I think there are no peers with genesis blocks Any idea?

You will not find any peer with genesis block for sure.

If you're having trouble using the `run-node.py` script, open it up and change the state-sync trust height delta. Sometimes going down helps, sometimes going up helps. Sometimes nothing helps.. 

Alternately, you can use a snapshot provider like [polkachu](https://polkachu.com/networks/sei)

**Comment by zfy0701** [comment]
> hi @mhmdbahja is your goal to join the network (you can use state sync info [here](https://www.docs.sei.io/dev-node/join-a-network)) or is your goal to sync from genesis? If it's from genesis, you'll have to start with the correct version of seid which would be `2.0.48beta`.

if that's the case how to use seidb from start?

**Comment by cordt-sei** [comment]
> > hi @mhmdbahja is your goal to join the network (you can use state sync info [here](https://www.docs.sei.io/dev-node/join-a-network)) or is your goal to sync from genesis? If it's from genesis, you'll have to start with the correct version of seid which would be `2.0.48beta`.
> 
> if that's the case how to use seidb from start?

You can't currently, the archive nodes are in the process of converting the db to that format. After this you will be able to sync, or to get a snapshot and not have to sync it yourself if that makes more sense.
