### ISSUE TITLE
panic: unknown field "inflation" in types.Minter

### ISSUE THREAD

**Issue by josedev-union** [sei-protocol/sei-chain#373]
## Error log
Failed to start seid with the following error.
```shell
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF starting node with ABCI Tendermint in-process
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting multiAppConn service impl=multiAppConn module=proxy
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting localClient service connection=query impl=localClient module=abci-client
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting EventBus service impl=EventBus module=events
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting PubSub service impl=PubSub module=pubsub
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF Starting IndexerService service impl=IndexerService module=txindex
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=1.2.4beta
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: 6:30PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: panic: unknown field "inflation" in types.Minter
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: goroutine 1 [running]:
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x36fd2c8?, {0xc0001aa690?, 0x0?, 0x0?}, {0x279c830?, 0xc0001fc4c0?})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/sei-protocol/sei-chain/x/mint.AppModule.InitGenesis({{{0x27b29b0, 0xc000eb3680}}, {{0x27af738, 0xc000eb3680}, {0x278c838, 0xc0011b0b80}, {{0x27af738, 0xc000eb3680}, 0xc0004f42a0, {0x278c838, ...}, ...}, ...}, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/sei-chain/x/mint/module.go:138 +0xa2
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x27a2668, 0xc000052070}, {0x27b0f40, 0xc0000c64c0}, {{0x0, 0x0}, {0xc0011aab40, 0xa}, 0x0, ...}, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/sei-protocol/sei-chain/app.(*App).InitChainer(_, {{0x27a2668, 0xc000052070}, {0x27b0f40, 0xc0000c64c0}, {{0x0, 0x0}, {0xc0011aab40, 0xa}, 0x0, ...}, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/sei-chain/app/app.go:836 +0x20e
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000df64e0, {{0x0, 0xeda5ee8c0, 0x0}, {0xc0011aab40, 0xa}, 0xc00018f280, {0x36fd2c8, 0x0, 0x0}, ...})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x455
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0001977a0, {{0x0, 0xeda5ee8c0, 0x0}, {0xc0011aab40, 0xa}, 0xc00018f280, {0x36fd2c8, 0x0, 0x0}, ...})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0x0, 0xeda5ee8c0, 0x0}, {0xc0011aab40, 0xa}, 0xc00018f280, {0x36fd2c8, 0x0, 0x0}, ...})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1e317e7, 0x7}}, {0xc0011aab40, 0xa}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000377fd0, {0x27b18b0, 0xc000ffa410})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1e317e7, 0x7}}, {0xc0011aab40, 0xa}, 0x1, 0x0, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/tendermint/tendermint/node.NewNode(0xc000138b40, {0x279f470, 0xc0004aff40}, 0xc000fe28d0, {0x2787400, 0xc00000f7d0}, 0x0?, 0x0?, 0xc000fe2ae0, {0x27a3778, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x27b84a8, 0xc0004a3710}, {0x0, 0x0}, {0x27a7818, 0xc0012b0f70}, ...}, ...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000308a00?, {0x36fd2c8?, 0x0?, 0x0?})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/spf13/cobra.(*Command).execute(0xc000308a00, {0x36fd2c8, 0x0, 0x0})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0001eca00)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/spf13/cobra.(*Command).Execute(...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0011aa640, 0x10})
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
Nov 04 18:30:10 sei-incentivized-0 seid[27229]: main.main()
Nov 04 18:30:10 sei-incentivized-0 seid[27229]:         /home/joseb/sei-chain/cmd/seid/main.go:16 +0x31
Nov 04 18:30:10 sei-incentivized-0 systemd[1]: seid.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
## version 
1.2.4beta

**Comment by navrik** [comment]
I have the same issue when trying to start seid
`root@ip-172-31-3-175:~/sei-chain# seid version --long | head
name: sei
server_name: <appd>
version: 1.2.3beta-13-g6fb8a28
commit: 6fb8a285da33de3654a85e58f9e78ae6cf44c31d
build_tags: netgo ledger,
go: go version go1.18.1 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/ChainSafe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d`

**Comment by msobh13** [comment]
same here 
panic: unknown field "inflation" in types.Minter

**Comment by philipsu522** [comment]
Apologies for the late response this is fixed in later versions! We're currently on **2.0.47beta** in sei-devnet-3 and atlantic-2
