### ISSUE TITLE
Error starting full node - panic: Failed to process committed block

### ISSUE THREAD

**Issue by heitorPB** [sei-protocol/sei-chain#490]
I followed the [online docs to setup a full node](https://docs.seinetwork.io/nodes-and-validators/joining-testnets) and when I try to start `seid` I get this error:

```
5:26PM INF commit synced commit=436F6D6D697449447B5B383320313231203134352031333520323139203233362032303420313534203135382031312032323120323530203720373620323137203131382031343020343620352032343620313533203520363620323038203336203134342031383020323035203136302039372031203232325D3A317D
5:26PM INF committed state app_hash=53799187DBECCC9A9E0BDDFA074CD9768C2E05F6990542D02490B4CDA06101DE height=1 module=state num_txs=0
5:26PM INF indexed block height=1 module=txindex
panic: Failed to process committed block (2:589B3CC74CD54E9AF2EF60FEB1E9BA84FC740839C2BA06BEE398144F9957E9F8): wrong Block.Header.AppHash.  Expected 53799187DBECCC9A9E0BDDFA074CD9768C2E05F6990542D02490B4CDA06101DE, got 21A58CC6051294964F25003C175F0330269CFA7B316BC7A441E206D0A7468FCA

goroutine 138 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0015141c0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/blockchain/v0/reactor.go:401 +0x123a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/blockchain/v0/reactor.go:110 +0x7a
```

Here's the full log: [seid.log](https://github.com/sei-protocol/sei-chain/files/10449188/seid.log)

If I ignore the error and simply try again, I still get error:

```bash
# seid start --moniker $MONIKER
5:51PM INF starting node with ABCI Tendermint in-process
5:51PM INF Starting multiAppConn service impl=multiAppConn module=proxy
5:51PM INF Starting localClient service connection=query impl=localClient module=abci-client
5:51PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
5:51PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
5:51PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
5:51PM INF Starting EventBus service impl=EventBus module=events
5:51PM INF Starting PubSub service impl=PubSub module=pubsub
5:51PM INF Starting IndexerService service impl=IndexerService module=txindex
5:51PM INF ABCI Handshake App Info hash="Sy����̚�\v��\aL�v�.\x05��\x05B�$��͠a\x01�" height=1 module=consensus protocol-version=0 software-version=1.1.1beta
5:51PM INF ABCI Replay Blocks appHeight=1 module=consensus stateHeight=1 storeHeight=2
5:51PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 53799187DBECCC9A9E0BDDFA074CD9768C2E05F6990542D02490B4CDA06101DE, got 21A58CC6051294964F25003C175F0330269CFA7B316BC7A441E206D0A7468FCA
```

There are similar open issues reported here: #32 and #372.

I got the genesis file from github, as per the instructions. Is that file up to date?

**Comment by philipsu522** [comment]
@heitorPB it seems like you may be on the wrong seid version. For atlantic-2 and sei-devnet-3, we're currently on **2.0.47beta** version. If you still have issues, please feel free to reach out on Discord: https://discord.com/invite/sei

**Comment by heitorPB** [comment]
@philipsu522 is atlantic-1 being phased out? I could not find any documentation about that. atlantic-2 shows as TBA in https://docs.seinetwork.io/nodes-and-validators/joining-testnets

**Comment by philipsu522** [comment]
@heitorPB yes, sorry! We are in the process of rewriting our documentation. If you want to join atlantic-2, there's a good guide written by one of our validators here: https://testnet-explorer.brocha.in/sei%20atlantic%202/statesync
