### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by meetrick** [sei-protocol/sei-chain#693]
# Incident - `panic: assignment to entry in nil map`
- The atlantic-2 validator node crashed with the following panic message.
If you try to add or modify a key-value pair in a map that has not been initialized or has been set to nil, you will get the "panic: assignment to entry in nil map" error message.
  -  It is assumed that the map was not initialized properly. This can harm the stability of the validator node and should be fixed.
```
9:22AM INF entering precommit step with invalid args current=5168653/0/RoundStepPrecommit entryLabel=precommit-two-thirds expected=#5168653/0 height=5168653 module=consensus round=0d=0 current=5168653/0/RoundStepPrecommit height=5168653 module=consensus
9:22AM INF commit is for a locked block; set ProposalBlock=LockedBlock block_hash=4E826AAFCEF37FF39561E3914E8B847D1EF9F2890D59C79D9D54D143B39077EB commit_round=0 height=5168653 module=consensus7FF39561E3914E8B847D1EF9F2890D59C79D9D54D143B39077EB height=5168653 module=consensus num_txs=25 root=87A0087F516C9B5C2F41B2BBAEBBAFB1CB0FAC5B28C385C0E6A3BC800CF97CC04268: connect: connection refused
9:22AM INF FinalizeBlock took 103ms
9:22AM INF finalized block block_app_hash=CE9AE13D7F6BADD7DF27AE93255310487842800E537ED99E40795ABC8C22310D height=5168653 latency_ms=103 module=state num_txs_res=25 num_val_updates=07F6BADD7DF27AE93255310487842800E537ED99E40795ABC8C22310D
9:22AM INF committed state block_app_hash=87A0087F516C9B5C2F41B2BBAEBBAFB1CB0FAC5B28C385C0E6A3BC800CF97CC0 height=5168653 module=state num_txs=25INF signed and pushed vote height=5168654 module=consensus round=0 vote={"block_id":{"hash":"E22A9ACC4B92031CC41B2DEE40E023D12EA10661C412FB0F322F1A9D03C27903","parts":{"hash":"7A9564C34873BAC1306B32F4705B2BBDE06481638868FD1A957DCDBF55D57A71","total":1}},"extension":null,"extension_signature":null,"height":"5168654","round":0,"signature":"LKZyDLtDsOCbuTaN8vOkGzX1qJHmQ/4bgJXY7rlOGjUkKuVKtpA/XbShQuZ+7K1d7lhvcGIbTEj3IiXQXwwVCg==","timestamp":"2023-04-08T07:22:49.132903589Z","type":2,"validator_address":"6557E859315448DB2DF93755C7D03F5CBF3BCC28","validator_index":7}
9:22AM INF entering precommit step with invalid args current=5168654/0/RoundStepPrecommit entryLabel=prevote-future expected=#5168654/0 height=5168654 module=consensus round=0
panic: assignment to entry in nil map

goroutine 9557 [running]:
github.com/tendermint/tendermint/internal/p2p.(*PeerManager).Add(0xc000c62280, {{0xc06f02ba48, 0x28}, {0xc06f02ba40, 0x5}, {0xc06f02ba71, 0x1b}, 0x6820, {0x0, 0x0}})
        /usr/local/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.2/internal/p2p/peermanager.go:435 +0x5a5
github.com/tendermint/tendermint/internal/p2p/pex.(*Reactor).handlePexMessage(0xc0003c5ad0, {0x2998db0, 0xc00055eb00}, 0xc13b5c5280, 0xc00719daa0?)
        /usr/local/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.2/internal/p2p/pex/reactor.go:303 +0x7ff
github.com/tendermint/tendermint/internal/p2p/pex.(*Reactor).processPexCh(0xc0003c5ad0, {0x2998db0?, 0xc00055eb00}, 0xc00719daa0)
        /usr/local/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.2/internal/p2p/pex/reactor.go:221 +0x528
created by github.com/tendermint/tendermint/internal/p2p/pex.(*Reactor).OnStart
        /usr/local/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.2/internal/p2p/pex/reactor.go:152 +0xd0
```

**Comment by philipsu522** [comment]
Thanks for this report! This should be resolved in https://github.com/sei-protocol/sei-tendermint/pull/134
